/*
 * Copyright (c) 2024 Realtek Semiconductor, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DRIVERS_SPI_SPI_RTS5817_M_CTRL_REG_H_
#define ZEPHYR_DRIVERS_SPI_SPI_RTS5817_M_CTRL_REG_H_

#define SPI_SSI_MST_BASE_ADDR           0x0
#define R_MST_SPI_SSI_START_CTRL        (SPI_SSI_MST_BASE_ADDR + 0X0000)
#define R_MST_SPI_SSI_STOP_CTRL         (SPI_SSI_MST_BASE_ADDR + 0X0004)
#define R_MST_SPI_SSI_RD_ADDR           (SPI_SSI_MST_BASE_ADDR + 0X0008)
#define R_MST_SPI_SSI_WR_ADDR           (SPI_SSI_MST_BASE_ADDR + 0X000C)
#define R_MST_SPI_SSI_DATA_LEN          (SPI_SSI_MST_BASE_ADDR + 0X0010)
#define R_MST_SPI_SSI_CONTROL           (SPI_SSI_MST_BASE_ADDR + 0X0014)
#define R_MST_SPI_SSI_IRQ_ENABLE        (SPI_SSI_MST_BASE_ADDR + 0X0018)
#define R_MST_SPI_SSI_IRQ_STATUS        (SPI_SSI_MST_BASE_ADDR + 0X001C)
#define R_MST_SPI_SSI_MS_SELECT         (SPI_SSI_MST_BASE_ADDR + 0X0020)
#define R_MST_SPI_SSI_DMA_STATE         (SPI_SSI_MST_BASE_ADDR + 0X0024)
#define R_MST_SPI_SSI_RD_FIFO_THERSHOLD (SPI_SSI_MST_BASE_ADDR + 0X0028)

/* Bits of R_MST_SPI_SSI_START_CTRL (0X0000) */

#define MST_SSI_START_OFFSET 0
#define MST_SSI_START_BITS   1
#define MST_SSI_START_MASK   (((1 << 1) - 1) << 0)
#define MST_SSI_START        (MST_SSI_START_MASK)

/* Bits of R_MST_SPI_SSI_STOP_CTRL (0X0004) */

#define MST_SSI_STOP_OFFSET 0
#define MST_SSI_STOP_BITS   1
#define MST_SSI_STOP_MASK   (((1 << 1) - 1) << 0)
#define MST_SSI_STOP        (MST_SSI_STOP_MASK)

/* Bits of R_MST_SPI_SSI_RD_ADDR (0X0008) */

#define MST_SSI_SRAM_RD_ADDR_OFFSET 0
#define MST_SSI_SRAM_RD_ADDR_BITS   32
#define MST_SSI_SRAM_RD_ADDR_MASK   (((1 << 32) - 1) << 0)
#define MST_SSI_SRAM_RD_ADDR        (MST_SSI_SRAM_RD_ADDR_MASK)

/* Bits of R_MST_SPI_SSI_WR_ADDR (0X000C) */

#define MST_SSI_SRAM_WR_ADDR_OFFSET 0
#define MST_SSI_SRAM_WR_ADDR_BITS   32
#define MST_SSI_SRAM_WR_ADDR_MASK   (((1 << 32) - 1) << 0)
#define MST_SSI_SRAM_WR_ADDR        (MST_SSI_SRAM_WR_ADDR_MASK)

/* Bits of R_MST_SPI_SSI_DATA_LEN (0X0010) */

#define MST_SSI_SRAM_LEN_OFFSET 0
#define MST_SSI_SRAM_LEN_BITS   32
#define MST_SSI_SRAM_LEN_MASK   (((1 << 32) - 1) << 0)
#define MST_SSI_SRAM_LEN        (MST_SSI_SRAM_LEN_MASK)

/* Bits of R_MST_SPI_SSI_CONTROL (0X0014) */

#define MST_SCK_INTERVAL_EN_OFFSET 0
#define MST_SCK_INTERVAL_EN_BITS   2
#define MST_SCK_INTERVAL_EN_MASK   (((1 << 2) - 1) << 0)
#define MST_SCK_INTERVAL_EN        (MST_SCK_INTERVAL_EN_MASK)

#define MST_SCK_COUNT_MAX_OFFSET 2
#define MST_SCK_COUNT_MAX_BITS   8
#define MST_SCK_COUNT_MAX_MASK   (((1 << 8) - 1) << 2)
#define MST_SCK_COUNT_MAX        (MST_SCK_COUNT_MAX_MASK)

#define MST_CK_COOLDOWN_OFFSET 10
#define MST_CK_COOLDOWN_BITS   8
#define MST_CK_COOLDOWN_MASK   (((1 << 8) - 1) << 10)
#define MST_CK_COOLDOWN        (MST_CK_COOLDOWN_MASK)

#define MST_FORCE_CS_N_OFFSET 18
#define MST_FORCE_CS_N_BITS   1
#define MST_FORCE_CS_N_MASK   (((1 << 1) - 1) << 18)
#define MST_FORCE_CS_N        (MST_FORCE_CS_N_MASK)

/* Bits of R_MST_SPI_SSI_IRQ_ENABLE (0X0018) */

#define MST_DONE_INT_ENABLE_OFFSET 0
#define MST_DONE_INT_ENABLE_BITS   1
#define MST_DONE_INT_ENABLE_MASK   (((1 << 1) - 1) << 0)
#define MST_DONE_INT_ENABLE        (MST_DONE_INT_ENABLE_MASK)

#define MST_SSI_WR_SRAM_OVERFLOW_ENABLE_OFFSET 1
#define MST_SSI_WR_SRAM_OVERFLOW_ENABLE_BITS   1
#define MST_SSI_WR_SRAM_OVERFLOW_ENABLE_MASK   (((1 << 1) - 1) << 1)
#define MST_SSI_WR_SRAM_OVERFLOW_ENABLE        (MST_SSI_WR_SRAM_OVERFLOW_ENABLE_MASK)

#define MST_SSI_RD_SRAM_UNDERFLOW_ENABLE_OFFSET 2
#define MST_SSI_RD_SRAM_UNDERFLOW_ENABLE_BITS   1
#define MST_SSI_RD_SRAM_UNDERFLOW_ENABLE_MASK   (((1 << 1) - 1) << 2)
#define MST_SSI_RD_SRAM_UNDERFLOW_ENABLE        (MST_SSI_RD_SRAM_UNDERFLOW_ENABLE_MASK)

/* Bits of R_MST_SPI_SSI_IRQ_STATUS (0X001C) */

#define MST_DONE_INT_OFFSET 0
#define MST_DONE_INT_BITS   1
#define MST_DONE_INT_MASK   (((1 << 1) - 1) << 0)
#define MST_DONE_INT        (MST_DONE_INT_MASK)

#define MST_SSI_WR_SRAM_OVERFLOW_OFFSET 1
#define MST_SSI_WR_SRAM_OVERFLOW_BITS   1
#define MST_SSI_WR_SRAM_OVERFLOW_MASK   (((1 << 1) - 1) << 1)
#define MST_SSI_WR_SRAM_OVERFLOW        (MST_SSI_WR_SRAM_OVERFLOW_MASK)

#define MST_SSI_RD_SRAM_UNDERFLOW_OFFSET 2
#define MST_SSI_RD_SRAM_UNDERFLOW_BITS   1
#define MST_SSI_RD_SRAM_UNDERFLOW_MASK   (((1 << 1) - 1) << 2)
#define MST_SSI_RD_SRAM_UNDERFLOW        (MST_SSI_RD_SRAM_UNDERFLOW_MASK)

/* Bits of R_MST_SPI_SSI_MS_SELECT (0X0020) */

#define MST_SSI_MS_SEL_OFFSET 0
#define MST_SSI_MS_SEL_BITS   1
#define MST_SSI_MS_SEL_MASK   (((1 << 1) - 1) << 0)
#define MST_SSI_MS_SEL        (MST_SSI_MS_SEL_MASK)

/* Bits of R_MST_SPI_SSI_DMA_STATE (0X0024) */

#define MST_RD_SRAM_STATE_OFFSET 0
#define MST_RD_SRAM_STATE_BITS   3
#define MST_RD_SRAM_STATE_MASK   (((1 << 3) - 1) << 0)
#define MST_RD_SRAM_STATE        (MST_RD_SRAM_STATE_MASK)

#define MST_WR_SRAM_STATE_OFFSET 8
#define MST_WR_SRAM_STATE_BITS   3
#define MST_WR_SRAM_STATE_MASK   (((1 << 3) - 1) << 8)
#define MST_WR_SRAM_STATE        (MST_WR_SRAM_STATE_MASK)

/* Bits of R_MST_SPI_SSI_RD_FIFO_THERSHOLD (0X0028) */

#define MST_SSI_RD_FIFO_THRESHOLD_OFFSET 0
#define MST_SSI_RD_FIFO_THRESHOLD_BITS   8
#define MST_SSI_RD_FIFO_THRESHOLD_MASK   (((1 << 8) - 1) << 0)
#define MST_SSI_RD_FIFO_THRESHOLD        (MST_SSI_RD_FIFO_THRESHOLD_MASK)

/***********************Definition created by FW**********************/
/* ssi master interrupt mask bits */
#define SSI_MST_INT_MASK                                                                           \
	(MST_DONE_INT_MASK | MST_SSI_WR_SRAM_OVERFLOW_MASK | MST_SSI_RD_SRAM_UNDERFLOW_MASK)

#endif /* ZEPHYR_DRIVERS_SPI_SPI_RTS5817_M_CTRL_REG_H_ */
