/*
 * Copyright (c) 2024 Realtek Semiconductor, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DRIVERS_FLASH_RTS5817_QSPI_REG_H_
#define ZEPHYR_DRIVERS_FLASH_RTS5817_QSPI_REG_H_

#define SPI_CACHE_BASE_ADDR 0x0
#define R_SPI_META_CTRL     (SPI_CACHE_BASE_ADDR + 0X0004)
#define R_SPI_CA_NUMBER     (SPI_CACHE_BASE_ADDR + 0X0008)
#define R_SPI_CONTROL       (SPI_CACHE_BASE_ADDR + 0X0010)
#define R_SPI_TCTL          (SPI_CACHE_BASE_ADDR + 0X0014)
#define R_SPI_CLK_DIVIDER   (SPI_CACHE_BASE_ADDR + 0X0018)
#define R_SPI_PAD_PULL_CTRL (SPI_CACHE_BASE_ADDR + 0X001C)
#define R_SPI_CRC_KEY       (SPI_CACHE_BASE_ADDR + 0X0020)
#define R_SPI_CRC_EN        (SPI_CACHE_BASE_ADDR + 0X0024)
#define R_SPI_CRC_OUT       (SPI_CACHE_BASE_ADDR + 0X0028)
#define R_SPI_COM_TRANSFER  (SPI_CACHE_BASE_ADDR + 0X002C)
#define R_SPI_SUB1_MODE     (SPI_CACHE_BASE_ADDR + 0X0030)
#define R_SPI_SUB1_COMMAND  (SPI_CACHE_BASE_ADDR + 0X0034)
#define R_SPI_SUB1_ADDR     (SPI_CACHE_BASE_ADDR + 0X0038)
#define R_SPI_SUB1_LENGTH   (SPI_CACHE_BASE_ADDR + 0X003C)
#define R_SPI_SUB2_MODE     (SPI_CACHE_BASE_ADDR + 0X0040)
#define R_SPI_SUB2_COMMAND  (SPI_CACHE_BASE_ADDR + 0X0044)
#define R_SPI_SUB2_ADDR     (SPI_CACHE_BASE_ADDR + 0X0048)
#define R_SPI_SUB2_LENGTH   (SPI_CACHE_BASE_ADDR + 0X004C)
#define R_SPI_SUB3_MODE     (SPI_CACHE_BASE_ADDR + 0X0050)
#define R_SPI_SUB3_COMMAND  (SPI_CACHE_BASE_ADDR + 0X0054)
#define R_SPI_SUB3_ADDR     (SPI_CACHE_BASE_ADDR + 0X0058)
#define R_SPI_SUB3_LENGTH   (SPI_CACHE_BASE_ADDR + 0X005C)
#define R_SPI_SUB4_MODE     (SPI_CACHE_BASE_ADDR + 0X0060)
#define R_SPI_SUB4_COMMAND  (SPI_CACHE_BASE_ADDR + 0X0064)
#define R_SPI_SUB4_ADDR     (SPI_CACHE_BASE_ADDR + 0X0068)
#define R_SPI_SUB4_LENGTH   (SPI_CACHE_BASE_ADDR + 0X006C)
#define R_SPI_INT_EN        (SPI_CACHE_BASE_ADDR + 0X0070)
#define R_SPI_INT_SR        (SPI_CACHE_BASE_ADDR + 0X0074)
#define R_SPI_WB_DMA_ADDR   (SPI_CACHE_BASE_ADDR + 0X0078)
#define R_SPI_WB_DMA_LEN    (SPI_CACHE_BASE_ADDR + 0X007C)
#define R_SPI_WB_DMA_DIR    (SPI_CACHE_BASE_ADDR + 0X0080)
#define R_SPI_COM_TCTL_1    (SPI_CACHE_BASE_ADDR + 0X0090)
#define R_SPI_COM_TCTL_2    (SPI_CACHE_BASE_ADDR + 0X0094)
#define R_SPI_TOP_CTL       (SPI_CACHE_BASE_ADDR + 0X0098)
#define R_SPI_SCK_AUTO_STOP (SPI_CACHE_BASE_ADDR + 0X009C)
#define R_SPI_AXI_M_CFG     (SPI_CACHE_BASE_ADDR + 0X00A0)

/* Bits of R_SPI_META_CTRL (0X0004) */

#define SPI_META_CONTENT_OFFSET 0
#define SPI_META_CONTENT_BITS   8
#define SPI_META_CONTENT_MASK   (((1 << 8) - 1) << 0)
#define SPI_META_CONTENT        (SPI_META_CONTENT_MASK)

#define SPI_META_LENGTH_OFFSET 8
#define SPI_META_LENGTH_BITS   4
#define SPI_META_LENGTH_MASK   (((1 << 4) - 1) << 8)
#define SPI_META_LENGTH        (SPI_META_LENGTH_MASK)

/* Bits of R_SPI_CA_NUMBER (0X0008) */

#define SPI_U_ADDR_BIT_NUM_OFFSET 0
#define SPI_U_ADDR_BIT_NUM_BITS   5
#define SPI_U_ADDR_BIT_NUM_MASK   (((1 << 5) - 1) << 0)
#define SPI_U_ADDR_BIT_NUM        (SPI_U_ADDR_BIT_NUM_MASK)

#define SPI_U_CMD_BIT_NUM_OFFSET 5
#define SPI_U_CMD_BIT_NUM_BITS   3
#define SPI_U_CMD_BIT_NUM_MASK   (((1 << 3) - 1) << 5)
#define SPI_U_CMD_BIT_NUM        (SPI_U_CMD_BIT_NUM_MASK)

/* Bits of R_SPI_CONTROL (0X0010) */

#define SPI_SOFT_RST_OFFSET 0
#define SPI_SOFT_RST_BITS   1
#define SPI_SOFT_RST_MASK   (((1 << 1) - 1) << 0)
#define SPI_SOFT_RST        (SPI_SOFT_RST_MASK)

#define SPI_MODE_OFFSET 2
#define SPI_MODE_BITS   2
#define SPI_MODE_MASK   (((1 << 2) - 1) << 2)
#define SPI_MODE        (SPI_MODE_MASK)

#define SPI_LSB_FIRST_OFFSET 5
#define SPI_LSB_FIRST_BITS   1
#define SPI_LSB_FIRST_MASK   (((1 << 1) - 1) << 5)
#define SPI_LSB_FIRST        (SPI_LSB_FIRST_MASK)

#define SPI_CS_POLARITY_OFFSET 6
#define SPI_CS_POLARITY_BITS   1
#define SPI_CS_POLARITY_MASK   (((1 << 1) - 1) << 6)
#define SPI_CS_POLARITY        (SPI_CS_POLARITY_MASK)

/* Bits of R_SPI_TCTL (0X0014) */

#define SPI_T_EDO_OFFSET 0
#define SPI_T_EDO_BITS   2
#define SPI_T_EDO_MASK   (((1 << 2) - 1) << 0)
#define SPI_T_EDO        (SPI_T_EDO_MASK)

#define SPI_T_CS_OFFSET 2
#define SPI_T_CS_BITS   2
#define SPI_T_CS_MASK   (((1 << 2) - 1) << 2)
#define SPI_T_CS        (SPI_T_CS_MASK)

#define SPI_U_DUM_BIT_NUM_OFFSET 8
#define SPI_U_DUM_BIT_NUM_BITS   5
#define SPI_U_DUM_BIT_NUM_MASK   (((1 << 5) - 1) << 8)
#define SPI_U_DUM_BIT_NUM        (SPI_U_DUM_BIT_NUM_MASK)

/* Bits of R_SPI_CLK_DIVIDER (0X0018) */

#define SPI_SCK_DIVIDER_OFFSET 0
#define SPI_SCK_DIVIDER_BITS   8
#define SPI_SCK_DIVIDER_MASK   (((1 << 8) - 1) << 0)
#define SPI_SCK_DIVIDER        (SPI_SCK_DIVIDER_MASK)

/* Bits of R_SPI_PAD_PULL_CTRL (0X001C) */

#define SPI_MISO_PULLCTL_OFFSET 0
#define SPI_MISO_PULLCTL_BITS   2
#define SPI_MISO_PULLCTL_MASK   (((1 << 2) - 1) << 0)
#define SPI_MISO_PULLCTL        (SPI_MISO_PULLCTL_MASK)

#define SPI_MOSI_PULLCTL_OFFSET 2
#define SPI_MOSI_PULLCTL_BITS   2
#define SPI_MOSI_PULLCTL_MASK   (((1 << 2) - 1) << 2)
#define SPI_MOSI_PULLCTL        (SPI_MOSI_PULLCTL_MASK)

#define SPI_SCK_PULLCTL_OFFSET 4
#define SPI_SCK_PULLCTL_BITS   2
#define SPI_SCK_PULLCTL_MASK   (((1 << 2) - 1) << 4)
#define SPI_SCK_PULLCTL        (SPI_SCK_PULLCTL_MASK)

#define SPI_CS_N_PULLCTL_OFFSET 6
#define SPI_CS_N_PULLCTL_BITS   2
#define SPI_CS_N_PULLCTL_MASK   (((1 << 2) - 1) << 6)
#define SPI_CS_N_PULLCTL        (SPI_CS_N_PULLCTL_MASK)

#define SPI_WP_N_PULLCTL_OFFSET 8
#define SPI_WP_N_PULLCTL_BITS   2
#define SPI_WP_N_PULLCTL_MASK   (((1 << 2) - 1) << 8)
#define SPI_WP_N_PULLCTL        (SPI_WP_N_PULLCTL_MASK)

#define SPI_HOLD_N_PULLCTL_OFFSET 10
#define SPI_HOLD_N_PULLCTL_BITS   2
#define SPI_HOLD_N_PULLCTL_MASK   (((1 << 2) - 1) << 10)
#define SPI_HOLD_N_PULLCTL        (SPI_HOLD_N_PULLCTL_MASK)

/* Bits of R_SPI_CRC_KEY (0X0020) */

#define SPI_CRC_KEY_OFFSET 0
#define SPI_CRC_KEY_BITS   32
#define SPI_CRC_KEY_MASK   (((1 << 32) - 1) << 0)
#define SPI_CRC_KEY        (SPI_CRC_KEY_MASK)

/* Bits of R_SPI_CRC_EN (0X0024) */

#define SPI_CRC_EN_OFFSET 0
#define SPI_CRC_EN_BITS   1
#define SPI_CRC_EN_MASK   (((1 << 1) - 1) << 0)
#define SPI_CRC_EN        (SPI_CRC_EN_MASK)

#define SPI_CRC_EN2_OFFSET 1
#define SPI_CRC_EN2_BITS   1
#define SPI_CRC_EN2_MASK   (((1 << 1) - 1) << 1)
#define SPI_CRC_EN2        (SPI_CRC_EN2_MASK)

/* Bits of R_SPI_CRC_OUT (0X0028) */

#define SPI_CRC_OUT_OFFSET 0
#define SPI_CRC_OUT_BITS   32
#define SPI_CRC_OUT_MASK   (((1 << 32) - 1) << 0)
#define SPI_CRC_OUT        (SPI_CRC_OUT_MASK)

/* Bits of R_SPI_COM_TRANSFER (0X002C) */

#define SPI_WB_TRANS_NUM_OFFSET 0
#define SPI_WB_TRANS_NUM_BITS   2
#define SPI_WB_TRANS_NUM_MASK   (((1 << 2) - 1) << 0)
#define SPI_WB_TRANS_NUM        (SPI_WB_TRANS_NUM_MASK)

#define SPI_WB_RST_OFFSET 2
#define SPI_WB_RST_BITS   1
#define SPI_WB_RST_MASK   (((1 << 1) - 1) << 2)
#define SPI_WB_RST        (SPI_WB_RST_MASK)

#define SPI_WB_TIMEOUT_OFFSET 3
#define SPI_WB_TIMEOUT_BITS   1
#define SPI_WB_TIMEOUT_MASK   (((1 << 1) - 1) << 3)
#define SPI_WB_TIMEOUT        (SPI_WB_TIMEOUT_MASK)

#define SPI_WB_IDLE_OFFSET 6
#define SPI_WB_IDLE_BITS   1
#define SPI_WB_IDLE_MASK   (((1 << 1) - 1) << 6)
#define SPI_WB_IDLE        (SPI_WB_IDLE_MASK)

#define SPI_WB_START_OFFSET 7
#define SPI_WB_START_BITS   1
#define SPI_WB_START_MASK   (((1 << 1) - 1) << 7)
#define SPI_WB_START        (SPI_WB_START_MASK)

/* Bits of R_SPI_SUB1_MODE (0X0030) */

#define SPI_WB_SUB_MODE1_OFFSET 0
#define SPI_WB_SUB_MODE1_BITS   4
#define SPI_WB_SUB_MODE1_MASK   (((1 << 4) - 1) << 0)
#define SPI_WB_SUB_MODE1        (SPI_WB_SUB_MODE1_MASK)

/* Bits of R_SPI_SUB1_COMMAND (0X0034) */

#define SPI_WB_SUB_CMD1_OFFSET 0
#define SPI_WB_SUB_CMD1_BITS   8
#define SPI_WB_SUB_CMD1_MASK   (((1 << 8) - 1) << 0)
#define SPI_WB_SUB_CMD1        (SPI_WB_SUB_CMD1_MASK)

/* Bits of R_SPI_SUB1_ADDR (0X0038) */

#define SPI_WB_SUB_ADDR1_OFFSET 0
#define SPI_WB_SUB_ADDR1_BITS   24
#define SPI_WB_SUB_ADDR1_MASK   (((1 << 24) - 1) << 0)
#define SPI_WB_SUB_ADDR1        (SPI_WB_SUB_ADDR1_MASK)

/* Bits of R_SPI_SUB1_LENGTH (0X003C) */

#define SPI_WB_SUB_LEN1_OFFSET 0
#define SPI_WB_SUB_LEN1_BITS   16
#define SPI_WB_SUB_LEN1_MASK   (((1 << 16) - 1) << 0)
#define SPI_WB_SUB_LEN1        (SPI_WB_SUB_LEN1_MASK)

/* Bits of R_SPI_SUB2_MODE (0X0040) */

#define SPI_WB_SUB_MODE2_OFFSET 0
#define SPI_WB_SUB_MODE2_BITS   4
#define SPI_WB_SUB_MODE2_MASK   (((1 << 4) - 1) << 0)
#define SPI_WB_SUB_MODE2        (SPI_WB_SUB_MODE2_MASK)

/* Bits of R_SPI_SUB2_COMMAND (0X0044) */

#define SPI_WB_SUB_CMD2_OFFSET 0
#define SPI_WB_SUB_CMD2_BITS   8
#define SPI_WB_SUB_CMD2_MASK   (((1 << 8) - 1) << 0)
#define SPI_WB_SUB_CMD2        (SPI_WB_SUB_CMD2_MASK)

/* Bits of R_SPI_SUB2_ADDR (0X0048) */

#define SPI_WB_SUB_ADDR2_OFFSET 0
#define SPI_WB_SUB_ADDR2_BITS   24
#define SPI_WB_SUB_ADDR2_MASK   (((1 << 24) - 1) << 0)
#define SPI_WB_SUB_ADDR2        (SPI_WB_SUB_ADDR2_MASK)

/* Bits of R_SPI_SUB2_LENGTH (0X004C) */

#define SPI_WB_SUB_LEN2_OFFSET 0
#define SPI_WB_SUB_LEN2_BITS   16
#define SPI_WB_SUB_LEN2_MASK   (((1 << 16) - 1) << 0)
#define SPI_WB_SUB_LEN2        (SPI_WB_SUB_LEN2_MASK)

/* Bits of R_SPI_SUB3_MODE (0X0050) */

#define SPI_WB_SUB_MODE3_OFFSET 0
#define SPI_WB_SUB_MODE3_BITS   4
#define SPI_WB_SUB_MODE3_MASK   (((1 << 4) - 1) << 0)
#define SPI_WB_SUB_MODE3        (SPI_WB_SUB_MODE3_MASK)

/* Bits of R_SPI_SUB3_COMMAND (0X0054) */

#define SPI_WB_SUB_CMD3_OFFSET 0
#define SPI_WB_SUB_CMD3_BITS   8
#define SPI_WB_SUB_CMD3_MASK   (((1 << 8) - 1) << 0)
#define SPI_WB_SUB_CMD3        (SPI_WB_SUB_CMD3_MASK)

/* Bits of R_SPI_SUB3_ADDR (0X0058) */

#define SPI_WB_SUB_ADDR3_OFFSET 0
#define SPI_WB_SUB_ADDR3_BITS   24
#define SPI_WB_SUB_ADDR3_MASK   (((1 << 24) - 1) << 0)
#define SPI_WB_SUB_ADDR3        (SPI_WB_SUB_ADDR3_MASK)

/* Bits of R_SPI_SUB3_LENGTH (0X005C) */

#define SPI_WB_SUB_LEN3_OFFSET 0
#define SPI_WB_SUB_LEN3_BITS   16
#define SPI_WB_SUB_LEN3_MASK   (((1 << 16) - 1) << 0)
#define SPI_WB_SUB_LEN3        (SPI_WB_SUB_LEN3_MASK)

/* Bits of R_SPI_SUB4_MODE (0X0060) */

#define SPI_WB_SUB_MODE4_OFFSET 0
#define SPI_WB_SUB_MODE4_BITS   4
#define SPI_WB_SUB_MODE4_MASK   (((1 << 4) - 1) << 0)
#define SPI_WB_SUB_MODE4        (SPI_WB_SUB_MODE4_MASK)

/* Bits of R_SPI_SUB4_COMMAND (0X0064) */

#define SPI_WB_SUB_CMD4_OFFSET 0
#define SPI_WB_SUB_CMD4_BITS   8
#define SPI_WB_SUB_CMD4_MASK   (((1 << 8) - 1) << 0)
#define SPI_WB_SUB_CMD4        (SPI_WB_SUB_CMD4_MASK)

/* Bits of R_SPI_SUB4_ADDR (0X0068) */

#define SPI_WB_SUB_ADDR4_OFFSET 0
#define SPI_WB_SUB_ADDR4_BITS   24
#define SPI_WB_SUB_ADDR4_MASK   (((1 << 24) - 1) << 0)
#define SPI_WB_SUB_ADDR4        (SPI_WB_SUB_ADDR4_MASK)

/* Bits of R_SPI_SUB4_LENGTH (0X006C) */

#define SPI_WB_SUB_LEN4_OFFSET 0
#define SPI_WB_SUB_LEN4_BITS   16
#define SPI_WB_SUB_LEN4_MASK   (((1 << 16) - 1) << 0)
#define SPI_WB_SUB_LEN4        (SPI_WB_SUB_LEN4_MASK)

/* Bits of R_SPI_INT_EN (0X0070) */

#define SPI_AUTO_READ_EXCEPTION_INT_EN_OFFSET 0
#define SPI_AUTO_READ_EXCEPTION_INT_EN_BITS   1
#define SPI_AUTO_READ_EXCEPTION_INT_EN_MASK   (((1 << 1) - 1) << 0)
#define SPI_AUTO_READ_EXCEPTION_INT_EN        (SPI_AUTO_READ_EXCEPTION_INT_EN_MASK)

#define SPI_AUTO_WRITE_EXCEPTION_INT_EN_OFFSET 1
#define SPI_AUTO_WRITE_EXCEPTION_INT_EN_BITS   1
#define SPI_AUTO_WRITE_EXCEPTION_INT_EN_MASK   (((1 << 1) - 1) << 1)
#define SPI_AUTO_WRITE_EXCEPTION_INT_EN        (SPI_AUTO_WRITE_EXCEPTION_INT_EN_MASK)

#define SPI_ERASE_EXCEPTION_INT_EN_OFFSET 2
#define SPI_ERASE_EXCEPTION_INT_EN_BITS   1
#define SPI_ERASE_EXCEPTION_INT_EN_MASK   (((1 << 1) - 1) << 2)
#define SPI_ERASE_EXCEPTION_INT_EN        (SPI_ERASE_EXCEPTION_INT_EN_MASK)

#define SPI_ERASE_CHIP_EXCEPTION_INT_EN_OFFSET 3
#define SPI_ERASE_CHIP_EXCEPTION_INT_EN_BITS   1
#define SPI_ERASE_CHIP_EXCEPTION_INT_EN_MASK   (((1 << 1) - 1) << 3)
#define SPI_ERASE_CHIP_EXCEPTION_INT_EN        (SPI_ERASE_CHIP_EXCEPTION_INT_EN_MASK)

#define SPI_USER_READ_EXCEPTION_INT_EN_OFFSET 4
#define SPI_USER_READ_EXCEPTION_INT_EN_BITS   1
#define SPI_USER_READ_EXCEPTION_INT_EN_MASK   (((1 << 1) - 1) << 4)
#define SPI_USER_READ_EXCEPTION_INT_EN        (SPI_USER_READ_EXCEPTION_INT_EN_MASK)

#define SPI_USER_WRITE_EXCEPTION_INT_EN_OFFSET 5
#define SPI_USER_WRITE_EXCEPTION_INT_EN_BITS   1
#define SPI_USER_WRITE_EXCEPTION_INT_EN_MASK   (((1 << 1) - 1) << 5)
#define SPI_USER_WRITE_EXCEPTION_INT_EN        (SPI_USER_WRITE_EXCEPTION_INT_EN_MASK)

#define SPI_OTHER_EXCEPTION_INT_EN_OFFSET 6
#define SPI_OTHER_EXCEPTION_INT_EN_BITS   1
#define SPI_OTHER_EXCEPTION_INT_EN_MASK   (((1 << 1) - 1) << 6)
#define SPI_OTHER_EXCEPTION_INT_EN        (SPI_OTHER_EXCEPTION_INT_EN_MASK)

#define SPI_DMA_INT_EN_OFFSET 7
#define SPI_DMA_INT_EN_BITS   1
#define SPI_DMA_INT_EN_MASK   (((1 << 1) - 1) << 7)
#define SPI_DMA_INT_EN        (SPI_DMA_INT_EN_MASK)

#define SPI_FIFO_AXI_OVERFLOW_EN_OFFSET 8
#define SPI_FIFO_AXI_OVERFLOW_EN_BITS   1
#define SPI_FIFO_AXI_OVERFLOW_EN_MASK   (((1 << 1) - 1) << 8)
#define SPI_FIFO_AXI_OVERFLOW_EN        (SPI_FIFO_AXI_OVERFLOW_EN_MASK)

#define SPI_FIFO_SPI_UNDERFLOW_EN_OFFSET 9
#define SPI_FIFO_SPI_UNDERFLOW_EN_BITS   1
#define SPI_FIFO_SPI_UNDERFLOW_EN_MASK   (((1 << 1) - 1) << 9)
#define SPI_FIFO_SPI_UNDERFLOW_EN        (SPI_FIFO_SPI_UNDERFLOW_EN_MASK)

#define SPI_FIFO_SPI_OVERFLOW_EN_OFFSET 10
#define SPI_FIFO_SPI_OVERFLOW_EN_BITS   1
#define SPI_FIFO_SPI_OVERFLOW_EN_MASK   (((1 << 1) - 1) << 10)
#define SPI_FIFO_SPI_OVERFLOW_EN        (SPI_FIFO_SPI_OVERFLOW_EN_MASK)

#define SPI_FIFO_AXI_UNDERFLOW_EN_OFFSET 11
#define SPI_FIFO_AXI_UNDERFLOW_EN_BITS   1
#define SPI_FIFO_AXI_UNDERFLOW_EN_MASK   (((1 << 1) - 1) << 11)
#define SPI_FIFO_AXI_UNDERFLOW_EN        (SPI_FIFO_AXI_UNDERFLOW_EN_MASK)

/* Bits of R_SPI_INT_SR (0X0074) */

#define SPI_AUTO_READ_EXCEPTION_INT_OFFSET 0
#define SPI_AUTO_READ_EXCEPTION_INT_BITS   1
#define SPI_AUTO_READ_EXCEPTION_INT_MASK   (((1 << 1) - 1) << 0)
#define SPI_AUTO_READ_EXCEPTION_INT        (SPI_AUTO_READ_EXCEPTION_INT_MASK)

#define SPI_AUTO_WRITE_EXCEPTION_INT_OFFSET 1
#define SPI_AUTO_WRITE_EXCEPTION_INT_BITS   1
#define SPI_AUTO_WRITE_EXCEPTION_INT_MASK   (((1 << 1) - 1) << 1)
#define SPI_AUTO_WRITE_EXCEPTION_INT        (SPI_AUTO_WRITE_EXCEPTION_INT_MASK)

#define SPI_ERASE_EXCEPTION_INT_OFFSET 2
#define SPI_ERASE_EXCEPTION_INT_BITS   1
#define SPI_ERASE_EXCEPTION_INT_MASK   (((1 << 1) - 1) << 2)
#define SPI_ERASE_EXCEPTION_INT        (SPI_ERASE_EXCEPTION_INT_MASK)

#define SPI_ERASE_CHIP_EXCEPTION_INT_OFFSET 3
#define SPI_ERASE_CHIP_EXCEPTION_INT_BITS   1
#define SPI_ERASE_CHIP_EXCEPTION_INT_MASK   (((1 << 1) - 1) << 3)
#define SPI_ERASE_CHIP_EXCEPTION_INT        (SPI_ERASE_CHIP_EXCEPTION_INT_MASK)

#define SPI_USER_READ_EXCEPTION_INT_OFFSET 4
#define SPI_USER_READ_EXCEPTION_INT_BITS   1
#define SPI_USER_READ_EXCEPTION_INT_MASK   (((1 << 1) - 1) << 4)
#define SPI_USER_READ_EXCEPTION_INT        (SPI_USER_READ_EXCEPTION_INT_MASK)

#define SPI_USER_WRITE_EXCEPTION_INT_OFFSET 5
#define SPI_USER_WRITE_EXCEPTION_INT_BITS   1
#define SPI_USER_WRITE_EXCEPTION_INT_MASK   (((1 << 1) - 1) << 5)
#define SPI_USER_WRITE_EXCEPTION_INT        (SPI_USER_WRITE_EXCEPTION_INT_MASK)

#define SPI_OTHER_EXCEPTION_INT_OFFSET 6
#define SPI_OTHER_EXCEPTION_INT_BITS   1
#define SPI_OTHER_EXCEPTION_INT_MASK   (((1 << 1) - 1) << 6)
#define SPI_OTHER_EXCEPTION_INT        (SPI_OTHER_EXCEPTION_INT_MASK)

#define SPI_DMA_INT_OFFSET 7
#define SPI_DMA_INT_BITS   1
#define SPI_DMA_INT_MASK   (((1 << 1) - 1) << 7)
#define SPI_DMA_INT        (SPI_DMA_INT_MASK)

#define SPI_FIFO_AXI_OVERFLOW_INT_OFFSET 8
#define SPI_FIFO_AXI_OVERFLOW_INT_BITS   1
#define SPI_FIFO_AXI_OVERFLOW_INT_MASK   (((1 << 1) - 1) << 8)
#define SPI_FIFO_AXI_OVERFLOW_INT        (SPI_FIFO_AXI_OVERFLOW_INT_MASK)

#define SPI_FIFO_SPI_UNDERFLOW_INT_OFFSET 9
#define SPI_FIFO_SPI_UNDERFLOW_INT_BITS   1
#define SPI_FIFO_SPI_UNDERFLOW_INT_MASK   (((1 << 1) - 1) << 9)
#define SPI_FIFO_SPI_UNDERFLOW_INT        (SPI_FIFO_SPI_UNDERFLOW_INT_MASK)

#define SPI_FIFO_SPI_OVERFLOW_INT_OFFSET 10
#define SPI_FIFO_SPI_OVERFLOW_INT_BITS   1
#define SPI_FIFO_SPI_OVERFLOW_INT_MASK   (((1 << 1) - 1) << 10)
#define SPI_FIFO_SPI_OVERFLOW_INT        (SPI_FIFO_SPI_OVERFLOW_INT_MASK)

#define SPI_FIFO_AXI_UNDERFLOW_INT_OFFSET 11
#define SPI_FIFO_AXI_UNDERFLOW_INT_BITS   1
#define SPI_FIFO_AXI_UNDERFLOW_INT_MASK   (((1 << 1) - 1) << 11)
#define SPI_FIFO_AXI_UNDERFLOW_INT        (SPI_FIFO_AXI_UNDERFLOW_INT_MASK)

/* Bits of R_SPI_WB_DMA_ADDR (0X0078) */

#define SPI_DMA_ADDR_OFFSET 0
#define SPI_DMA_ADDR_BITS   32
#define SPI_DMA_ADDR_MASK   (((1 << 32) - 1) << 0)
#define SPI_DMA_ADDR        (SPI_DMA_ADDR_MASK)

/* Bits of R_SPI_WB_DMA_LEN (0X007C) */

#define SPI_DMA_LEN_OFFSET 0
#define SPI_DMA_LEN_BITS   16
#define SPI_DMA_LEN_MASK   (((1 << 16) - 1) << 0)
#define SPI_DMA_LEN        (SPI_DMA_LEN_MASK)

/* Bits of R_SPI_WB_DMA_DIR (0X0080) */

#define SPI_DMA_DIR_OFFSET 0
#define SPI_DMA_DIR_BITS   1
#define SPI_DMA_DIR_MASK   (((1 << 1) - 1) << 0)
#define SPI_DMA_DIR        (SPI_DMA_DIR_MASK)

/* Bits of R_SPI_COM_TCTL_1 (0X0090) */

#define SPI_CMD_GD_TIME_OFFSET 0
#define SPI_CMD_GD_TIME_BITS   8
#define SPI_CMD_GD_TIME_MASK   (((1 << 8) - 1) << 0)
#define SPI_CMD_GD_TIME        (SPI_CMD_GD_TIME_MASK)

/* Bits of R_SPI_COM_TCTL_2 (0X0094) */

#define SPI_WB_GD_TIME_OFFSET 0
#define SPI_WB_GD_TIME_BITS   8
#define SPI_WB_GD_TIME_MASK   (((1 << 8) - 1) << 0)
#define SPI_WB_GD_TIME        (SPI_WB_GD_TIME_MASK)

/* Bits of R_SPI_TOP_CTL (0X0098) */

#define SPI_OP_TIME_OFFSET 0
#define SPI_OP_TIME_BITS   8
#define SPI_OP_TIME_MASK   (((1 << 8) - 1) << 0)
#define SPI_OP_TIME        (SPI_OP_TIME_MASK)

/* Bits of R_SPI_SCK_AUTO_STOP (0X009C) */

#define SPI_ENABLE_CLOCK_PAUSE_OFFSET 0
#define SPI_ENABLE_CLOCK_PAUSE_BITS   1
#define SPI_ENABLE_CLOCK_PAUSE_MASK   (((1 << 1) - 1) << 0)
#define SPI_ENABLE_CLOCK_PAUSE        (SPI_ENABLE_CLOCK_PAUSE_MASK)

/* Bits of R_SPI_AXI_M_CFG (0X00A0) */

#define SPI_AXIM_AWCACHE_CFG_OFFSET 0
#define SPI_AXIM_AWCACHE_CFG_BITS   4
#define SPI_AXIM_AWCACHE_CFG_MASK   (((1 << 4) - 1) << 0)
#define SPI_AXIM_AWCACHE_CFG        (SPI_AXIM_AWCACHE_CFG_MASK)

#define SPI_AXIM_ARCACHE_CFG_OFFSET 4
#define SPI_AXIM_ARCACHE_CFG_BITS   4
#define SPI_AXIM_ARCACHE_CFG_MASK   (((1 << 4) - 1) << 4)
#define SPI_AXIM_ARCACHE_CFG        (SPI_AXIM_ARCACHE_CFG_MASK)

/* Parameters definition */

/* Parametsers of R_SPI_COM_TRANSFER (0X002C)*/

#define SPI_COM_TRANSFER_NUM_1 0x00UL
#define SPI_COM_TRANSFER_NUM_2 0x01UL
#define SPI_COM_TRANSFER_NUM_3 0x02UL
#define SPI_COM_TRANSFER_NUM_4 0x03UL

/* Parametsers of R_SPI_WB_DMA_DIR (0X0080) */

#define SPI_TO_DTCM 0
#define DTCM_TO_SPI SPI_DMA_DIR

#endif /* ZEPHYR_DRIVERS_FLASH_RTS5817_QSPI_REG_H_ */
