/*
 * Copyright (c) 2025 Realtek Semiconductor, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef DRIVERS_ENTROPY_ENTROPY_RTS5817_H
#define DRIVERS_ENTROPY_ENTROPY_RTS5817_H

#define R_PUF_SYS_RNG_VERSION      0x00
#define R_PUF_SYS_RNG_FEATURE      0x08
#define R_PUF_SYS_RNG_STATUS       0x10
#define R_PUF_SYS_RNG_ENABLE       0x20
#define R_PUF_SYS_RNG_CONFIG       0x24
#define R_PUF_SYS_RNG_TEST_CFG0    0x30
#define R_PUF_SYS_RNG_TEST_CFG1    0x38
#define R_PUF_SYS_RNG_TEST_CFG2    0x3c
#define R_PUF_SYS_RNG_TEST_REPORT0 0x40
#define R_PUF_SYS_RNG_TEST_REPORT1 0x44
#define R_PUF_SYS_RNG_TEST_REPORT2 0x50
#define R_PUF_SYS_RNG_TEST_REPORT3 0x54
#define R_PUF_SYS_RNG_TEST_REPORT4 0x58
#define R_PUF_SYS_RNG_TEST_REPORT5 0x5c
#define R_PUF_SYS_RNG_TEST_REPORT6 0x60
#define R_PUF_SYS_RNG_TEST_REPORT7 0x64
#define R_PUF_SYS_RNG_FIFO_CLEAR   0x6c
#define R_PUF_SYS_RNG_DATA_OUT     0x70

/* Bits of R_PUF_SYS_RNG_STATUS (0x10) */
#define PUF_SYS_RNG_IDLE_OFFSET 0UL
#define PUF_SYS_RNG_IDLE        BIT(0)

#define PUF_SYS_FIFO_CLEARED_OFFSET 1UL
#define PUF_SYS_FIFO_CLEARED        BIT(1)

#define PUF_SYS_ENTROPY_AVAILABLE_OFFSET 2UL
#define PUF_SYS_ENTROPY_AVAILABLE        BIT(2)

#define PUF_SYS_B_FIFO_AVAILABLE_OFFSET 4UL
#define PUF_SYS_B_FIFO_AVAILABLE        BIT(4)

#define PUF_SYS_A_FIFO_AVAILABLE_OFFSET 5UL
#define PUF_SYS_A_FIFO_AVAILABLE        BIT(5)

#define PUF_SYS_A_FIFO_FULL_OFFSET 6UL
#define PUF_SYS_A_FIFO_FULL        BIT(6)

#define PUF_SYS_RNG_IS_ENABLED_OFFSET 8UL
#define PUF_SYS_RNG_IS_ENABLED        BIT(8)

#define PUF_SYS_RNG_HEALTH_TEST_ACTIVE_OFFSET 9UL
#define PUF_SYS_RNG_HEALTH_TEST_ACTIVE        BIT(9)

#define PUF_SYS_GENERATING_RANDOM_DATA_OFFSET 10UL
#define PUF_SYS_GENERATING_RANDOM_DATA        BIT(10)

#define PUF_SYS_RNG_HALTED_OFFSET 11UL
#define PUF_SYS_RNG_HALTED        BIT(11)

/* Bits of R_PUF_SYS_RNG_ENABLE (0x20) */
#define PUF_SYS_RNG_FUN_EN_OFFSET 0UL
#define PUF_SYS_RNG_FUN_EN        BIT(0)

#define PUF_SYS_RNG_CLK_EN_OFFSET 1UL
#define PUF_SYS_RNG_CLK_EN        BIT(1)

#define PUF_SYS_RNG_OUT_EN_OFFSET 2UL
#define PUF_SYS_RNG_OUT_EN        BIT(2)

/* Bits of R_PUF_SYS_RNG_FIFO_CLEAR (0x6c) */

#define PUF_SYS_RNG_HT_CLR_OFFSET 0UL
#define PUF_SYS_RNG_HT_CLR        BIT(0)

#endif /* DRIVERS_ENTROPY_ENTROPY_RTS5817_H */
