/*
 * Copyright (c) 2025 Realtek Semiconductor, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef __ZEPHYR_INCLUDE_DRIVERS_RTS5817_FLASH_API_EXTENSIONS_H__
#define __ZEPHYR_INCLUDE_DRIVERS_RTS5817_FLASH_API_EXTENSIONS_H__

enum flash_rts5817_ex_ops {
	FLASH_RTS5817_EX_OP_WR_SR = FLASH_EX_OP_VENDOR_BASE,
	FLASH_RTS5817_EX_OP_RD_SR,
	FLASH_RTS5817_EX_OP_SOFT_PROTECT,
	FLASH_RTS5817_EX_OP_WP_PIN_SET,
	FLASH_RTS5817_EX_OP_WP_PIN_GET,
};

enum flash_rts5817_wp_state {
	FLASH_RTS5817_WP_LOW = 0,
	FLASH_RTS5817_WP_HIGH = 1,
};

#endif /* __ZEPHYR_INCLUDE_DRIVERS_RTS5817_FLASH_API_EXTENSIONS_H__ */
